// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.33.4
// source: proto/tempconv.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TempConverter_Convert_FullMethodName = "/tempconv.v1.TempConverter/Convert"
	TempConverter_Health_FullMethodName  = "/tempconv.v1.TempConverter/Health"
)

// TempConverterClient is the client API for TempConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TempConverterClient interface {
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type tempConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewTempConverterClient(cc grpc.ClientConnInterface) TempConverterClient {
	return &tempConverterClient{cc}
}

func (c *tempConverterClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, TempConverter_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempConverterClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TempConverter_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TempConverterServer is the server API for TempConverter service.
// All implementations must embed UnimplementedTempConverterServer
// for forward compatibility
type TempConverterServer interface {
	Convert(context.Context, *ConvertRequest) (*ConvertResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedTempConverterServer()
}

// UnimplementedTempConverterServer must be embedded to have forward compatible implementations.
type UnimplementedTempConverterServer struct {
}

func (UnimplementedTempConverterServer) Convert(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedTempConverterServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTempConverterServer) mustEmbedUnimplementedTempConverterServer() {}

// UnsafeTempConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TempConverterServer will
// result in compilation errors.
type UnsafeTempConverterServer interface {
	mustEmbedUnimplementedTempConverterServer()
}

func RegisterTempConverterServer(s grpc.ServiceRegistrar, srv TempConverterServer) {
	s.RegisterService(&TempConverter_ServiceDesc, srv)
}

func _TempConverter_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempConverterServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempConverter_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempConverterServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempConverter_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempConverterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempConverter_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempConverterServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TempConverter_ServiceDesc is the grpc.ServiceDesc for TempConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TempConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempconv.v1.TempConverter",
	HandlerType: (*TempConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _TempConverter_Convert_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TempConverter_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tempconv.proto",
}
